# Generated by Django 4.1.3 on 2023-03-01 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrower_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_borrowing', models.DecimalField(decimal_places=2, max_digits=7)),
                ('investment_interest', models.DecimalField(decimal_places=2, max_digits=7)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_period_start', models.DateField()),
                ('payement_period_end', models.DateField()),
                ('active', models.BooleanField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MoneyBorrower', to='loan.borroweraccount')),
            ],
        ),
        migrations.CreateModel(
            name='LoanShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('processed', models.BooleanField()),
                ('for_loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_invested_in', to='loan.loanrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.UUIDField()),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid', models.BooleanField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanPayingFor', to='loan.borroweraccount')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_cash', models.DecimalField(decimal_places=2, max_digits=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
