# Generated by Django 4.1.7 on 2023-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoraccount',
            name='account_id',
            field=models.IntegerField(null=True),
        ),
    ]
